In [3]:
l=[23,45,67,-79,45]

In [4]:
l

[23, 45, 67, -79, 45]

In [5]:
import numpy as np

In [6]:
a=np.array(l)

In [7]:
a

array([ 23,  45,  67, -79,  45])

In [8]:
a

array([ 23,  45,  67, -79,  45])

In [26]:
b=np.array([2,3.4,465,True,"so"])

In [27]:
b

array(['2', '3.4', '465', 'True', 'so'], dtype='<U32')

In [15]:
print(b)

['2' '3.4' 'theh' '465' 'True']


In [16]:
l.pop()

45

In [17]:
l

[23, 45, 67, -79]

In [18]:
a.mean()

20.2

In [34]:
c=np.array([-24,3.4,465])

In [35]:
c

array([-24. ,   3.4, 465. ])

In [36]:
c.min()

-24.0

In [37]:
c.max()

465.0

In [38]:
l

[23, 45, 67, -79]

In [39]:
a

array([ 23,  45,  67, -79,  45])

In [40]:
a[:2]

array([23, 45])

In [41]:
a[2:4]

array([ 67, -79])

In [42]:
a

array([ 23,  45,  67, -79,  45])

In [43]:
b=a[:]

In [44]:
b

array([ 23,  45,  67, -79,  45])

In [45]:
b[0]=333

In [46]:
b

array([333,  45,  67, -79,  45])

In [47]:
#the value gets assigned to a in order to save the storage memory
a

array([333,  45,  67, -79,  45])

In [48]:
c=a.copy()

In [49]:
c

array([333,  45,  67, -79,  45])

In [50]:
c[0]=123

In [51]:
c

array([123,  45,  67, -79,  45])

In [52]:
a

array([333,  45,  67, -79,  45])

In [28]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
import tensorflow as tf
print(tf.version.VERSION)

ImportError: Traceback (most recent call last):
  File "C:\Users\Public\anacon\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.